
package cinematicketbookingsystem.Forms.CustomerForms;

import cinematicketbookingsystem.Forms.Login;
import cinematicketbookingsystem.Model.Cart;
import cinematicketbookingsystem.Model.Movie;
import cinematicketbookingsystem.Utility;
import javax.swing.JOptionPane;


public class CinemaSeatTicketView extends javax.swing.JFrame {

    /**
     * Creates new form CinemaSeatTicketView
     */
    Movie movieData = null;
    int seatNumber = 0;
    
    public CinemaSeatTicketView(int movieId, int seatNum) {
        initComponents();
        movieData = Utility.databaseInteraction.getMoviesDataById(movieId);
        seatNumber = seatNum;
        if (movieData == null) {
            JOptionPane.showConfirmDialog(null, "Something went wrong", "Movie Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            lbl_MovieName.setText(movieData.getM_Name());
            lbl_Date.setText(movieData.getM_Date().toLocaleString().substring(0,movieData.getM_Date().toLocaleString().indexOf("12:00:00")) + " - " + movieData.getM_Time());
            lbl_Price.setText("₪ : " + movieData.getM_Price());
            lbl_HallName.setText(Utility.databaseInteraction.getHallDataById(movieData.getM_HId()).getH_Name());
            lbl_TicketType.setText(Utility.databaseInteraction.getTicketTypeDataById(movieData.getM_TId()).getT_Name());
            lbl_SeatNumber.setText("" + seatNum);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_TicketType = new javax.swing.JLabel();
        lbl_MovieName = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        lbl_HallName = new javax.swing.JLabel();
        btn_MainMenuView = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btn_Logout = new javax.swing.JButton();
        lbl_Price = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_SeatNumber = new javax.swing.JLabel();
        btn_BackToHall = new javax.swing.JButton();
        btn_AddToCart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Current Seat Ticket View");

        jLabel1.setFont(new java.awt.Font("Ink Free", 3, 36)); // NOI18N
        jLabel1.setText("Cinema Ticket View");

        jLabel5.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel5.setText("Hall Name");

        jLabel2.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel2.setText("Movies Name");

        jLabel3.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel3.setText("Ticket Type");

        jLabel4.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel4.setText("Date Time");

        lbl_TicketType.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        lbl_TicketType.setForeground(new java.awt.Color(255, 51, 51));
        lbl_TicketType.setText("Diamond");

        lbl_MovieName.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        lbl_MovieName.setForeground(new java.awt.Color(255, 51, 102));
        lbl_MovieName.setText("Harry Potter");

        lbl_Date.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        lbl_Date.setForeground(new java.awt.Color(255, 51, 51));
        lbl_Date.setText("4 April, 2021 - 10:10:10");

        lbl_HallName.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        lbl_HallName.setForeground(new java.awt.Color(255, 51, 51));
        lbl_HallName.setText("Hall 1");

        btn_MainMenuView.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        btn_MainMenuView.setText("Main");
        btn_MainMenuView.setBorder(new javax.swing.border.MatteBorder(null));
        btn_MainMenuView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_MainMenuView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MainMenuViewActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel10.setText("Price");

        btn_Logout.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        btn_Logout.setText("Logout");
        btn_Logout.setBorder(new javax.swing.border.MatteBorder(null));
        btn_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });

        lbl_Price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Price.setForeground(new java.awt.Color(255, 51, 51));
        lbl_Price.setText("₪: 123.00");

        jLabel12.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel12.setText("Seat No");

        lbl_SeatNumber.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        lbl_SeatNumber.setForeground(new java.awt.Color(255, 51, 51));
        lbl_SeatNumber.setText("1");

        btn_BackToHall.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        btn_BackToHall.setText("Back To Hall View");
        btn_BackToHall.setBorder(new javax.swing.border.MatteBorder(null));
        btn_BackToHall.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_BackToHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackToHallActionPerformed(evt);
            }
        });

        btn_AddToCart.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        btn_AddToCart.setText("Add To Cart");
        btn_AddToCart.setBorder(new javax.swing.border.MatteBorder(null));
        btn_AddToCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddToCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_MainMenuView, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_SeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_MovieName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_TicketType, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_HallName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_BackToHall, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(btn_AddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(420, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MainMenuView, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_MovieName)
                            .addComponent(jLabel4)
                            .addComponent(lbl_Date))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TicketType)
                            .addComponent(jLabel5)
                            .addComponent(lbl_HallName))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbl_Price)
                    .addComponent(jLabel12)
                    .addComponent(lbl_SeatNumber))
                .addGap(18, 18, 18)
                .addComponent(btn_BackToHall, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(247, Short.MAX_VALUE)
                    .addComponent(btn_AddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MainMenuViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MainMenuViewActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainCustomerView().setVisible(true);
    }//GEN-LAST:event_btn_MainMenuViewActionPerformed

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void btn_BackToHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackToHallActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CinemaHallView(movieData.getM_Id()).setVisible(true);
    }//GEN-LAST:event_btn_BackToHallActionPerformed

    private void btn_AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddToCartActionPerformed
        // TODO add your handling code here:
        Utility.cartData.add(new Cart(movieData, seatNumber));
        JOptionPane.showConfirmDialog(null, "Seat " + seatNumber + " for movie " + movieData.getM_Name() + " added to cart.", "Movie Added", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        new CinemaHallView(movieData.getM_Id()).setVisible(true);
    }//GEN-LAST:event_btn_AddToCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CinemaSeatTicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CinemaSeatTicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CinemaSeatTicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CinemaSeatTicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CinemaSeatTicketView(1, 1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddToCart;
    private javax.swing.JButton btn_BackToHall;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_MainMenuView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_HallName;
    private javax.swing.JLabel lbl_MovieName;
    private javax.swing.JLabel lbl_Price;
    private javax.swing.JLabel lbl_SeatNumber;
    private javax.swing.JLabel lbl_TicketType;
    // End of variables declaration//GEN-END:variables
}
