package cinematicketbookingsystem.Forms.CustomerForms;

import cinematicketbookingsystem.Forms.Login;
import cinematicketbookingsystem.Model.Card;
import cinematicketbookingsystem.Model.Cash;
import cinematicketbookingsystem.Utility;
import javax.swing.JOptionPane;

public class PaymentMethod extends javax.swing.JFrame {

    /**
     * Creates new form PaymentMethod
     */
    public PaymentMethod() {
        initComponents();
        if (Utility.cartData.isEmpty()) {
            this.dispose();
            new MainCustomerView().setVisible(true);
        }
        txt_TotalPrice.setText("₪ : " + Utility.databaseInteraction.calculateTotalCartPrice());
        txt_TotalPrice.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_Pay = new javax.swing.JButton();
        btn_Logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmb_CardType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_HolderName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_CCV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_CardNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_TotalPrice = new javax.swing.JTextField();
        btn_MainView = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        chk_Popcorn = new javax.swing.JCheckBox();
        chk_Drink = new javax.swing.JCheckBox();
        txt_PopcornQty = new com.toedter.components.JSpinField();
        txt_DrinkQty = new com.toedter.components.JSpinField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment");

        jLabel1.setFont(new java.awt.Font("Ink Free", 3, 36)); // NOI18N
        jLabel1.setText("Payment Method");
        jLabel1.setToolTipText("");

        btn_Pay.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        btn_Pay.setText("Pay");
        btn_Pay.setBorder(new javax.swing.border.MatteBorder(null));
        btn_Pay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PayActionPerformed(evt);
            }
        });

        btn_Logout.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        btn_Logout.setText("Logout");
        btn_Logout.setBorder(new javax.swing.border.MatteBorder(null));
        btn_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel2.setText("Card Type");

        cmb_CardType.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        cmb_CardType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Master Card", "Cash" }));
        cmb_CardType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_CardTypeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel3.setText("Holder Name");

        txt_HolderName.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel4.setText("CCV");
        jLabel4.setToolTipText("");

        txt_CCV.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel5.setText("Card Number");

        txt_CardNumber.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel6.setText("Total ");

        txt_TotalPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_MainView.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        btn_MainView.setText("Main");
        btn_MainView.setBorder(new javax.swing.border.MatteBorder(null));
        btn_MainView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_MainView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MainViewActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel7.setText("Food");
        jLabel7.setToolTipText("");

        chk_Popcorn.setText("Popcorn");
        chk_Popcorn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_PopcornActionPerformed(evt);
            }
        });

        chk_Drink.setText("Drink");
        chk_Drink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_DrinkActionPerformed(evt);
            }
        });

        txt_PopcornQty.setMinimum(0);
        txt_PopcornQty.setValue(1);
        txt_PopcornQty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_PopcornQtyMouseClicked(evt);
            }
        });
        txt_PopcornQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PopcornQtyKeyPressed(evt);
            }
        });

        txt_DrinkQty.setMinimum(0);
        txt_DrinkQty.setValue(1);
        txt_DrinkQty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_DrinkQtyMouseClicked(evt);
            }
        });
        txt_DrinkQty.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_DrinkQtyPropertyChange(evt);
            }
        });
        txt_DrinkQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_DrinkQtyKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_MainView, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_HolderName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb_CardType, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_CCV))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_CardNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_DrinkQty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_TotalPrice)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(chk_Drink)
                                            .addGap(63, 63, 63)
                                            .addComponent(chk_Popcorn)
                                            .addGap(31, 31, 31))))))
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_PopcornQty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MainView, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_CardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_HolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_CCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_CardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chk_Drink)
                    .addComponent(chk_Popcorn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_PopcornQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_DrinkQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PayActionPerformed
        // TODO add your handling code here:
        if (cmb_CardType.getSelectedIndex() == 0) {
            if ("".equals(txt_HolderName.getText())) {
                JOptionPane.showConfirmDialog(null, "Enter Card Holder Name ", "Card Holder Name Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                return;
            } else if ("".equals(txt_CCV.getText())) {
                JOptionPane.showConfirmDialog(null, "Enter CCV Number ", "CCV Number Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                return;
            } else if ("".equals(txt_CardNumber.getText())) {
                JOptionPane.showConfirmDialog(null, "Enter Card Number ", "Card Number Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            int row = Utility.databaseInteraction.insertPaymentDetails(new Card(0, 0, txt_HolderName.getText(), txt_CCV.getText(), txt_CardNumber.getText()), txt_DrinkQty.getValue(), txt_PopcornQty.getValue());
            if (row > 0) {
                JOptionPane.showConfirmDialog(null, "Order  Placed Successfully.", "Success", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                Utility.cartData.clear();
            } else {
                JOptionPane.showConfirmDialog(null, "Order Not Placed.", "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            int row = Utility.databaseInteraction.insertPaymentDetails(new Cash(0, 0), txt_DrinkQty.getValue(), txt_PopcornQty.getValue());
            if (row > 0) {
                JOptionPane.showConfirmDialog(null, "Order  Placed Successfully.", "Success", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                Utility.cartData.clear();
            } else {
                JOptionPane.showConfirmDialog(null, "Order Not Placed.", "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            }
        }
        this.dispose();
        new MainCustomerView().setVisible(true);
    }//GEN-LAST:event_btn_PayActionPerformed

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void btn_MainViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MainViewActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainCustomerView().setVisible(true);
    }//GEN-LAST:event_btn_MainViewActionPerformed

    private void cmb_CardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_CardTypeActionPerformed
        // TODO add your handling code here:
        if (cmb_CardType.getSelectedIndex() == 0) {
            txt_CCV.setEnabled(true);
            txt_CardNumber.setEnabled(true);
            txt_HolderName.setEnabled(true);
        } else {

            txt_CCV.setEnabled(false);
            txt_CardNumber.setEnabled(false);
            txt_HolderName.setEnabled(false);
        }
    }//GEN-LAST:event_cmb_CardTypeActionPerformed

    public void calculateTotalPrice() {
        double total = Utility.databaseInteraction.calculateTotalCartPrice();
        total += txt_DrinkQty.getValue() * Utility.DRINKPRICE;
        total += txt_PopcornQty.getValue() * Utility.POPCORNPRICE;
        txt_TotalPrice.setText("₪ : " + total);
    }


    private void chk_DrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_DrinkActionPerformed
        // TODO add your handling code here:
        if (chk_Drink.isSelected()) {
            txt_DrinkQty.setEnabled(true);
            txt_DrinkQty.setValue(1);
        } else {
            txt_DrinkQty.setEnabled(false);
            txt_DrinkQty.setValue(0);
        }
    }//GEN-LAST:event_chk_DrinkActionPerformed

    private void chk_PopcornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_PopcornActionPerformed
        // TODO add your handling code here:
        if (chk_Popcorn.isSelected()) {
            txt_PopcornQty.setEnabled(true);
            txt_PopcornQty.setValue(1);
        } else {
            txt_PopcornQty.setEnabled(false);
            txt_PopcornQty.setValue(0);
        }
    }//GEN-LAST:event_chk_PopcornActionPerformed

    private void txt_DrinkQtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_DrinkQtyMouseClicked
        // TODO add your handling code here:
        calculateTotalPrice();
    }//GEN-LAST:event_txt_DrinkQtyMouseClicked

    private void txt_PopcornQtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_PopcornQtyMouseClicked
        // TODO add your handling code here:
         calculateTotalPrice();
    }//GEN-LAST:event_txt_PopcornQtyMouseClicked

    private void txt_PopcornQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PopcornQtyKeyPressed
        // TODO add your handling code here:
         calculateTotalPrice();
    }//GEN-LAST:event_txt_PopcornQtyKeyPressed

    private void txt_DrinkQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DrinkQtyKeyPressed
        // TODO add your handling code here:
         calculateTotalPrice();
    }//GEN-LAST:event_txt_DrinkQtyKeyPressed

    private void txt_DrinkQtyPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_DrinkQtyPropertyChange
        // TODO add your handling code here:
        calculateTotalPrice();
    }//GEN-LAST:event_txt_DrinkQtyPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentMethod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_MainView;
    private javax.swing.JButton btn_Pay;
    private javax.swing.JCheckBox chk_Drink;
    private javax.swing.JCheckBox chk_Popcorn;
    private javax.swing.JComboBox<String> cmb_CardType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_CCV;
    private javax.swing.JTextField txt_CardNumber;
    private com.toedter.components.JSpinField txt_DrinkQty;
    private javax.swing.JTextField txt_HolderName;
    private com.toedter.components.JSpinField txt_PopcornQty;
    private javax.swing.JTextField txt_TotalPrice;
    // End of variables declaration//GEN-END:variables
}
