
package cinematicketbookingsystem.Forms.AdminForms;

import cinematicketbookingsystem.Forms.Login;
import cinematicketbookingsystem.Model.*;
import cinematicketbookingsystem.Utility;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.*;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;


public class AddMovie extends javax.swing.JFrame {

    /**
     * Creates new form AddMovie
     */
    private String movieImagePath = "";

    public AddMovie() {
        initComponents();
        for (Hall hall : Utility.databaseInteraction.getAllHallData()) {
            cmb_HallName.addItem(hall.getH_Name());
        }

        for (TicketType ticketType : Utility.databaseInteraction.getAllTicketTypeData()) {
            cmb_TicketType.addItem(ticketType.getT_Name());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txt_Price = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_Image = new javax.swing.JButton();
        btn_Logout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Time = new javax.swing.JTextField();
        cmb_TicketType = new javax.swing.JComboBox<>();
        btn_Main = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmb_HallName = new javax.swing.JComboBox<>();
        lbl_MovieImage = new javax.swing.JLabel();
        btn_AddMovie = new javax.swing.JButton();
        txt_Date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Movie");

        jLabel4.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel4.setText("Ticket Price");
        jLabel4.setToolTipText("");

        txt_Price.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ink Free", 3, 36)); // NOI18N
        jLabel1.setText("Add Movie");
        jLabel1.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel5.setText("Date");

        btn_Image.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        btn_Image.setText("Add Image");
        btn_Image.setBorder(new javax.swing.border.MatteBorder(null));
        btn_Image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImageActionPerformed(evt);
            }
        });

        btn_Logout.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        btn_Logout.setText("Logout");
        btn_Logout.setBorder(new javax.swing.border.MatteBorder(null));
        btn_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel6.setText("Time");

        jLabel2.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel2.setText("Ticket Type");

        txt_Time.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        cmb_TicketType.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        cmb_TicketType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_TicketTypeActionPerformed(evt);
            }
        });

        btn_Main.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        btn_Main.setText("Main");
        btn_Main.setBorder(new javax.swing.border.MatteBorder(null));
        btn_Main.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MainActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel3.setText("Movie Name");

        txt_Name.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel7.setText("Hall Name");

        cmb_HallName.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        lbl_MovieImage.setText("                         Movie Image");
        lbl_MovieImage.setMaximumSize(new java.awt.Dimension(22, 77));
        lbl_MovieImage.setMinimumSize(new java.awt.Dimension(22, 77));

        btn_AddMovie.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        btn_AddMovie.setText("Add Movie");
        btn_AddMovie.setBorder(new javax.swing.border.MatteBorder(null));
        btn_AddMovie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_AddMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddMovieActionPerformed(evt);
            }
        });

        txt_Date.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btn_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_Name))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmb_TicketType, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_Price))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb_HallName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(lbl_MovieImage, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_AddMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(txt_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmb_TicketType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmb_HallName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbl_MovieImage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btn_AddMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImageActionPerformed
        try {
            // TODO add your handling code here:
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            movieImagePath = f.getAbsolutePath();

            try {
                scaleImage(movieImagePath, lbl_MovieImage, lbl_MovieImage.getWidth(), lbl_MovieImage.getHeight());
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            String date = new java.util.Date().toString().replace(' ', '_').replace(',', '_').replace(':', '_');
            movieImagePath = "MovieImages\\" + date + "_" + f.getName();
            File file = new File(movieImagePath);
            BufferedImage image = ImageIO.read(f.getAbsoluteFile());
            boolean saves = ImageIO.write(image, f.getName().substring(f.getName().indexOf(".") + 1), file);  // ignore returned boolean
            //    saveImage(movieImagePath, f.getName());
            //    JOptionPane.showConfirmDialog(null, movieImagePath = f.getName());
        } catch (IOException ex) {
            Logger.getLogger(AddMovie.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AddMovie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ImageActionPerformed


    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void btn_MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MainActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainAdminView().setVisible(true);
    }//GEN-LAST:event_btn_MainActionPerformed

    private void cmb_TicketTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_TicketTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_TicketTypeActionPerformed

    private void scaleImage(String location, JLabel label, int width, int height) {
        ImageIcon icon = new ImageIcon(location);
        Image img = icon.getImage();

        Image imgScale = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        label.setIcon(scaledIcon);

    }

    private void btn_AddMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddMovieActionPerformed
        // TODO add your handling code here:
        if ("".equals(txt_Name.getText())) {
            JOptionPane.showConfirmDialog(null, "Enter Movies Name", "Movie Name Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        } else if ("".equals(getAndValidateTime())) {
            JOptionPane.showConfirmDialog(null, "Enter valid Movies Time {00:00} format ", "Movie Time Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        } else if (getAndValidatePrice() <= 0) {

        } else if (getAndValidateDate() == null) {

        } else if (cmb_HallName.getSelectedIndex() == -1) {
            JOptionPane.showConfirmDialog(null, "Enter Hall Data Before Proceeding", "Hall Data Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new AddHall().setVisible(true);
        } else if ("".equals(movieImagePath)) {
            JOptionPane.showConfirmDialog(null, "Add Movie Image", "Image Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        } else {
            int insertedRow = Utility.databaseInteraction.insertMovieData(new Movie(0, txt_Name.getText(), getAndValidateDate(), txt_Time
                    .getText(), Double.parseDouble(txt_Price.getText()), Utility.databaseInteraction.getTicketTypeNameId(cmb_TicketType.getSelectedItem().toString()), Utility.databaseInteraction.validateAndGetHallNameIdExist(cmb_HallName.getSelectedItem().toString()), movieImagePath, false));
            if (insertedRow > 0) {
                JOptionPane.showConfirmDialog(null, "Movie Added Successfully", "Success Messages", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
           this.dispose();
           new ViewAllMovies().setVisible(true);
            } else {
                JOptionPane.showConfirmDialog(null, "Movie not  Added Successfully", "Movie Insertion Error Messages", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            }
            
        }

    }//GEN-LAST:event_btn_AddMovieActionPerformed
    public String getAndValidateTime() {
        if (!txt_Time.getText().matches("\\d{2}:\\d{2}")) {
            return "";
        }
        return txt_Time.getText();
    }

    public Date getAndValidateDate() {
        Date d = null;
        try {
            int day = txt_Date.getDate().getDate();
            int month = txt_Date.getDate().getMonth();
            int year = txt_Date.getDate().getYear();

            d = Date.valueOf((year - 100 + 2000) + "-" + (month + 1) + "-" + day);

            if (d == null) {
                JOptionPane.showConfirmDialog(null, "Invalid Date", "Date Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            } else {
                Date currentDate = new java.sql.Date(new java.util.Date().getTime());

                if (d.before(currentDate)) {
                    if (d.getDate() == currentDate.getDate() && d.getMonth() == currentDate.getMonth() && d.getYear() == currentDate.getYear()) {
                    } else {
                        JOptionPane.showConfirmDialog(null, "Date Should be greater than or equal to today", "Date Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                        return null;
                    }
                }

            }
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(null, "Invalid Date", "Date Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
        return d;
    }

    public double getAndValidatePrice() {
        double price = -1;
        try {
            price = Double.parseDouble(txt_Price.getText());
            if (price <= 0) {
                JOptionPane.showConfirmDialog(null, "Price should be greater than 0", "Price Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(null, "Enter valid Price", "Price Error", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
        return price;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddMovie;
    private javax.swing.JButton btn_Image;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_Main;
    private javax.swing.JComboBox<String> cmb_HallName;
    private javax.swing.JComboBox<String> cmb_TicketType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_MovieImage;
    private com.toedter.calendar.JDateChooser txt_Date;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_Price;
    private javax.swing.JTextField txt_Time;
    // End of variables declaration//GEN-END:variables
}
